[package]
name = "aci-map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.23.0"
itertools = "0.10.5"
gif = "0.12.0"
